### ISSUE TITLE
[Feature Request] Custom District Names on a per board basis

### ISSUE THREAD

**Issue by Deflaktor** [FortuneStreetModding/csmm-qt#12]
E.g. instead of District A-L we have things like Sun / Mercury etc 

requested by ZaSpai

**Comment by MysticMismagius** [comment]
![image](https://user-images.githubusercontent.com/78046059/146989214-b299e62c-725d-4863-bd57-b8d452e54b29.png)
Feature is not fully functional, the gray bar still makes line breaks every few characters rather than displaying the whole district name on one line

**Comment by Landmaster** [comment]
feature now works in 1.4.1
