### ISSUE TITLE
[Bug] CSMM does not fully support re-editing an exported game and does not warn the user

### ISSUE THREAD

**Issue by Deflaktor** [FortuneStreetModding/csmm-qt#13]

**Comment by MysticMismagius** [comment]
Note for readers: Def has mentioned that the double-dipping glitches in and of themselves will probably never be fixed

The plan is to detect whether a ROM imported into CSMM has already been CSMM-modded before, and throw up an error to prevent people from double-dipping.

**Comment by Landmaster** [comment]
1.6.4
