### ISSUE TITLE
[QOL] CSMM Help button links to the csmm-qt wiki, which has no pages

### ISSUE THREAD

**Issue by MysticMismagius** [FortuneStreetModding/csmm-qt#24]
[The csmm-qt wiki](https://github.com/FortuneStreetModding/csmm-qt/wiki) has nothing in it but a failsafe link to the actual wiki that I had to add in after someone complained that the `CSMM Help` button was useless.

Since [all of the actual Custom Street modding tutorials are on the Fortune Avenue wiki,](https://github.com/FortuneStreetModding/fortune-avenue-qt/wiki) the `CSMM Help` button should link there.

**Comment by Deflaktor** [comment]
implemented with 9f4a8f7e5e0b7d158fd5adf9be90bc81d3a88e5a
