### ISSUE TITLE
Restoring Features of Older Fortune Street Editors

### ISSUE THREAD

**Issue by TheBouncyBob** [FortuneStreetModding/csmm-qt#29]
It's been a while since I've used Fortune Street Avenue, so I may not be truely up to date with the latest version. I do remember prefering it over the old one, but found the older one to still have important functions the new one couldn't do, making it the one I used to actually make stages after plotting them out in Fortune Street Avenue. Mainly, these two features seem to be lost overtime:

One thing that the older versions did was not automatically update the price when the value of a shop was changed. It would be really nice if this wasn't always automatic in the newer versions, maybe as a way to toggle it on and off. Sometimes, when making board ballances, you just want to raise or lower shop prices and not values, sometimes even on a large scale all across the board. This is a real pain to work with when it always is adjusting your prices whenever you change the value, especially as the older vesion didn't do this. (Also, being able to set a custom yeild equasion would be awesome, as well, as I personally like to give lesser traversed districts have higher price to value yeilds.)

Another thing the older version did was let you enter in which shop name ID the shop was going to use, from 1-100, even letting you use the unused shop names which you could edit and use in the text file of the game for yourself. The latest version I had used had a drop down menu which only let you pick from the list of exsisting shopnames, disallowing the use of the unused shops. This also flows into what I was saying before, but just by changing the Property Name of the square, it ALSO updates the price info and value, making it very tedious process to update all the shop names of a stage with different names without adjusting shop prices and values, since then you also have to go back and manually adjust all the values and shop prices again. The drop down menu is certainly a great tool for beginners, but as someone who knows that changing shop names in the older versions is just so much better for making name tweaks, I avoid using the drop down bar entirely and make shop name adjustments by using the older versions. It would be amazing for a way to include the unused shops in the newer version and have a toggle to stop auto updating the shop info about them when you change their name.

**Comment by Deflaktor** [comment]
Hi Bouncybob. This is the issue tracker for csmm. Can you post this issue over at fortune avenue.
