### ISSUE TITLE
Benzin memory leaks

### ISSUE THREAD

**Issue by Landmaster** [FortuneStreetModding/csmm-qt#35]
CSMM uses benzin to process brylt files, but benzin is currently riddled with memory leaks. Might consider using https://www.hboehm.info/gc/ to help with patching those leaks.

**Comment by Deflaktor** [comment]
![giphy](https://user-images.githubusercontent.com/4169014/151726261-0bf85a72-fde8-4255-8be6-17d45733a645.gif)
