### ISSUE TITLE
[Feature Request] Increase added map limit of 16

### ISSUE THREAD

**Issue by widardd** [FortuneStreetModding/csmm-qt#4]
I don't know if this limitation is a hardware limitation on the wii, but would it be possible to increase this limit?
Tried ignoring this warning by CSMM, but Dolphin crashed the moment I tried to go past the standard maps.

**Comment by Landmaster** [comment]
Increased the map limit to 32 per zone (and 66 total per mapset)

**Comment by Landmaster** [comment]
removed the map limit entirely
