### ISSUE TITLE
Wiimfi patcher doesn't work on newest version of CSMM (1.3.0)

### ISSUE THREAD

**Issue by MysticMismagius** [FortuneStreetModding/csmm-qt#6]
Proof: ![image](https://cdn.discordapp.com/attachments/708085079980900476/868207091683328020/Screen_Shot_2021-07-23_at_3.01.27_PM.png)
![image](https://user-images.githubusercontent.com/78046059/127096258-5d08b024-f24b-45e1-a654-858204e994b6.png)

This occurred twice when patching a vanilla ISO using CSMM. The "Patch Wiimfi" option was checked.

**Comment by Deflaktor** [comment]
Have you clicked on "re-download tools" in the file context menu within csmm to update to newest wit tool version?

**Comment by MysticMismagius** [comment]
I had not done that when I wrote this. I just tested it and it seems to have worked now.
