### ISSUE TITLE
[Bug] CSMM Crashes at 80% when building iso/wbfs in 3.0.3

### ISSUE THREAD

**Issue by Sophilautia** [FortuneStreetModding/csmm-qt#71]
New issue, for some reason CSMM crashes when exporting an iso/wbfs at 80% progress. However, even though it crashes, the iso/wbfs saves successfully. It's pretty inconvenient when I'm regularly exporting wbfs files for testing, and it's bound to cause confusion for other users.

This doesn't occur when exporting to a folder or using quick setup.

**Comment by nikkiwritescode** [comment]
I believe this was fixed in 3.0.4, so I'm closing the issue. (I assigned Deflaktor to it to give him credit as I believe he was the one who fixed it)

**Comment by Sophilautia** [comment]
While this doesn't seem to occur in the latest csmm, I've noticed now that csmm doesn't seem to give any dialogue for completing the build process.
