### ISSUE TITLE
Change default from 'Open Folder' to 'Open WBFS/ISO'

### ISSUE THREAD

**Issue by Sophilautia** [FortuneStreetModding/csmm-qt#74]
In both the File menu and Quick Setup menus of CSMM, for some reason Open Folder comes first before Open WBFS/ISO. This has been known to confuse many end users and result in a lot of clutter in the Modding Issues channel. I believe Open WBFS/ISO should be the first option in both cases.

![image](https://user-images.githubusercontent.com/10488699/228069525-38eddd3c-605a-42e2-97eb-41b8696025ee.png)

![image](https://user-images.githubusercontent.com/10488699/228069562-9d5528cd-6826-4df7-83fa-59b50652d3d7.png)

**Comment by Landmaster** [comment]
3.1.1
