### ISSUE TITLE
CSMM won't cancel in Windows

### ISSUE THREAD

**Issue by nikkiwritescode** [FortuneStreetModding/csmm-qt#77]
When applying CSWT (or another operation) the progress bar window has a Close (X) button on it. Clicking this, however, doesn't cancel the operation -- it just pops back up the next time there is an update to the window to be made.

It should either:
1) Cancel the operation, or
2) Be greyed out so it can't be clicked

**Comment by Landmaster** [comment]
The 2nd option is implemented, but I'm leaving this open as the 1st option is planned to be implemented eventually.
